#include "Player/ASCharacter.h"
#include "Combat/ASHealthComponent.h"
#include "Combat/ASWeaponComponent.h"
#include "Interaction/ASInteractable.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Engine/World.h"
AASCharacter::AASCharacter(){PrimaryActorTick.bCanEverTick=true;bReplicates=true;SetReplicateMovement(true);GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;GetCharacterMovement()->bOrientRotationToMovement=false;bUseControllerRotationYaw=true;CameraBoom=CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));CameraBoom->SetupAttachment(RootComponent);CameraBoom->TargetArmLength=360.f;CameraBoom->bUsePawnControlRotation=true;FollowCamera=CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));FollowCamera->SetupAttachment(CameraBoom,USpringArmComponent::SocketName);Health=CreateDefaultSubobject<UASHealthComponent>(TEXT("Health"));Weapon=CreateDefaultSubobject<UASWeaponComponent>(TEXT("Weapon"));}
void AASCharacter::BeginPlay(){Super::BeginPlay();GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;}
void AASCharacter::Tick(float D){Super::Tick(D);if(bFireHeld)FireOnce();}
void AASCharacter::SetupPlayerInputComponent(UInputComponent*I){Super::SetupPlayerInputComponent(I);I->BindAxis("MoveForward",this,&AASCharacter::MoveForward);I->BindAxis("MoveRight",this,&AASCharacter::MoveRight);I->BindAxis("Turn",this,&AASCharacter::Turn);I->BindAxis("LookUp",this,&AASCharacter::LookUp);I->BindAction("Jump",IE_Pressed,this,&ACharacter::Jump);I->BindAction("Jump",IE_Released,this,&ACharacter::StopJumping);I->BindAction("Sprint",IE_Pressed,this,&AASCharacter::SprintPressed);I->BindAction("Sprint",IE_Released,this,&AASCharacter::SprintReleased);I->BindAction("Fire",IE_Pressed,this,&AASCharacter::FirePressed);I->BindAction("Fire",IE_Released,this,&AASCharacter::FireReleased);I->BindAction("Dash",IE_Pressed,this,&AASCharacter::Dash);I->BindAction("Reload",IE_Pressed,this,&AASCharacter::Reload);I->BindAction("Interact",IE_Pressed,this,&AASCharacter::Interact);}
void AASCharacter::MoveForward(float V){if(Controller&&V!=0)AddMovementInput(GetActorForwardVector(),V);}void AASCharacter::MoveRight(float V){if(Controller&&V!=0)AddMovementInput(GetActorRightVector(),V);}void AASCharacter::Turn(float V){AddControllerYawInput(V);}void AASCharacter::LookUp(float V){AddControllerPitchInput(V);}void AASCharacter::SprintPressed(){bSprintHeld=true;GetCharacterMovement()->MaxWalkSpeed=SprintSpeed;}void AASCharacter::SprintReleased(){bSprintHeld=false;GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;}void AASCharacter::FirePressed(){bFireHeld=true;FireOnce();}void AASCharacter::FireReleased(){bFireHeld=false;}
void AASCharacter::Dash(){if(!GetWorld())return;double N=GetWorld()->GetTimeSeconds();if(N-LastDashTime<DashCooldown)return;LastDashTime=N;LaunchCharacter(GetActorForwardVector()*DashStrength+FVector(0,0,80),true,false);}void AASCharacter::FireOnce(){if(!Weapon||!Controller)return;FVector L;FRotator R;Controller->GetPlayerViewPoint(L,R);Weapon->RequestFire(L,R.Vector());}void AASCharacter::Reload(){if(Weapon)Weapon->RequestReload();}
void AASCharacter::Interact(){if(!Controller||!GetWorld())return;FVector L;FRotator R;Controller->GetPlayerViewPoint(L,R);FHitResult H;FCollisionQueryParams Q(SCENE_QUERY_STAT(ASInteract),true,this);if(GetWorld()->LineTraceSingleByChannel(H,L,L+R.Vector()*InteractDistance,ECC_Visibility,Q)&&H.GetActor()&&H.GetActor()->GetClass()->ImplementsInterface(UASInteractable::StaticClass()))IASInteractable::Execute_Interact(H.GetActor(),this);}
