#include "Player/ASCharacter.h"
#include "Combat/ASHealthComponent.h"
#include "Combat/ASWeaponComponent.h"
#include "Combat/ASWeaponInventoryComponent.h"
#include "Combat/ASGrenade.h"
#include "Game/ASGameMode.h"
#include "Interaction/ASInteractable.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/PlayerState.h"
#include "Player/ASPlayerState.h"
#include "Net/UnrealNetwork.h"
#include "Engine/World.h"
#include "TimerManager.h"
AASCharacter::AASCharacter(){PrimaryActorTick.bCanEverTick=true;bReplicates=true;SetReplicateMovement(true);GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;GetCharacterMovement()->bOrientRotationToMovement=false;bUseControllerRotationYaw=true;CameraBoom=CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));CameraBoom->SetupAttachment(RootComponent);CameraBoom->TargetArmLength=360.f;CameraBoom->bUsePawnControlRotation=true;FollowCamera=CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));FollowCamera->SetupAttachment(CameraBoom,USpringArmComponent::SocketName);Health=CreateDefaultSubobject<UASHealthComponent>(TEXT("Health"));Weapon=CreateDefaultSubobject<UASWeaponComponent>(TEXT("Weapon"));Inventory=CreateDefaultSubobject<UASWeaponInventoryComponent>(TEXT("Inventory"));}
void AASCharacter::BeginPlay(){Super::BeginPlay();GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;Grenades=MaxGrenades;if(Health)Health->OnDeath.AddDynamic(this,&AASCharacter::HandleHealthDeath);}
void AASCharacter::EndPlay(const EEndPlayReason::Type EndPlayReason){GetWorldTimerManager().ClearTimer(BleedoutTimer);Super::EndPlay(EndPlayReason);}
void AASCharacter::Tick(float D){Super::Tick(D);if(bFireHeld&&!bDowned&&!bEliminated)FireOnce();}
void AASCharacter::SetupPlayerInputComponent(UInputComponent*I){Super::SetupPlayerInputComponent(I);I->BindAxis("MoveForward",this,&AASCharacter::MoveForward);I->BindAxis("MoveRight",this,&AASCharacter::MoveRight);I->BindAxis("Turn",this,&AASCharacter::Turn);I->BindAxis("LookUp",this,&AASCharacter::LookUp);I->BindAction("Jump",IE_Pressed,this,&ACharacter::Jump);I->BindAction("Jump",IE_Released,this,&ACharacter::StopJumping);I->BindAction("Sprint",IE_Pressed,this,&AASCharacter::SprintPressed);I->BindAction("Sprint",IE_Released,this,&AASCharacter::SprintReleased);I->BindAction("Fire",IE_Pressed,this,&AASCharacter::FirePressed);I->BindAction("Fire",IE_Released,this,&AASCharacter::FireReleased);I->BindAction("Dash",IE_Pressed,this,&AASCharacter::Dash);I->BindAction("Reload",IE_Pressed,this,&AASCharacter::Reload);I->BindAction("Interact",IE_Pressed,this,&AASCharacter::Interact);I->BindAction("Grenade",IE_Pressed,this,&AASCharacter::ThrowGrenade);I->BindAction("Weapon1",IE_Pressed,this,&AASCharacter::EquipSlot1);I->BindAction("Weapon2",IE_Pressed,this,&AASCharacter::EquipSlot2);I->BindAction("Weapon3",IE_Pressed,this,&AASCharacter::EquipSlot3);I->BindAction("Weapon4",IE_Pressed,this,&AASCharacter::EquipSlot4);}
void AASCharacter::MoveForward(float V){if(Controller&&V!=0&&!bDowned&&!bEliminated)AddMovementInput(GetActorForwardVector(),V);}void AASCharacter::MoveRight(float V){if(Controller&&V!=0&&!bDowned&&!bEliminated)AddMovementInput(GetActorRightVector(),V);}void AASCharacter::Turn(float V){AddControllerYawInput(V);}void AASCharacter::LookUp(float V){AddControllerPitchInput(V);}void AASCharacter::SprintPressed(){if(bDowned||bEliminated)return;bSprintHeld=true;GetCharacterMovement()->MaxWalkSpeed=SprintSpeed;}void AASCharacter::SprintReleased(){bSprintHeld=false;GetCharacterMovement()->MaxWalkSpeed=WalkSpeed;}void AASCharacter::FirePressed(){if(bDowned||bEliminated)return;bFireHeld=true;FireOnce();}void AASCharacter::FireReleased(){bFireHeld=false;}
void AASCharacter::Dash(){if(bDowned||bEliminated||!GetWorld())return;double N=GetWorld()->GetTimeSeconds();if(N-LastDashTime<DashCooldown)return;LastDashTime=N;LaunchCharacter(GetActorForwardVector()*DashStrength+FVector(0,0,80),true,false);}void AASCharacter::FireOnce(){if(!Weapon||!Controller||bDowned||bEliminated)return;FVector L;FRotator R;Controller->GetPlayerViewPoint(L,R);Weapon->RequestFire(L,R.Vector());}void AASCharacter::Reload(){if(Weapon&&!bDowned&&!bEliminated)Weapon->RequestReload();}
void AASCharacter::Interact(){if(!Controller||!GetWorld()||bDowned||bEliminated)return;FVector L;FRotator R;Controller->GetPlayerViewPoint(L,R);if(HasAuthority())ServerInteract_Implementation(L,R.Vector());else ServerInteract(L,R.Vector());}
void AASCharacter::ServerInteract_Implementation(FVector_NetQuantize O,FVector_NetQuantizeNormal D){if(bDowned||bEliminated||FVector::DistSquared(O,GetActorLocation())>FMath::Square(700.f)||!GetWorld())return;FHitResult H;FCollisionQueryParams Q(SCENE_QUERY_STAT(ASServerInteract),true,this);if(GetWorld()->LineTraceSingleByChannel(H,O,O+D*InteractDistance,ECC_Visibility,Q)&&H.GetActor()){if(AASCharacter*Target=Cast<AASCharacter>(H.GetActor())){Target->TryReviveFrom(this);return;}if(H.GetActor()->GetClass()->ImplementsInterface(UASInteractable::StaticClass()))IASInteractable::Execute_Interact(H.GetActor(),this);}}
void AASCharacter::ThrowGrenade(){if(!Controller||bDowned||bEliminated||Grenades<=0)return;FVector L;FRotator R;Controller->GetPlayerViewPoint(L,R);if(HasAuthority())ServerThrowGrenade_Implementation(L,R.Vector());else ServerThrowGrenade(L,R.Vector());}
void AASCharacter::ServerThrowGrenade_Implementation(FVector_NetQuantize O,FVector_NetQuantizeNormal D){if(bDowned||bEliminated||!GrenadeClass||Grenades<=0||FVector::DistSquared(O,GetActorLocation())>FMath::Square(700.f)||!GetWorld())return;Grenades--;FActorSpawnParameters P;P.Owner=this;P.Instigator=this;GetWorld()->SpawnActor<AASGrenade>(GrenadeClass,O+D*70.f,D.Rotation()+FRotator(-12,0,0),P);}
void AASCharacter::EquipSlot1(){if(Inventory&&!bDowned&&!bEliminated)Inventory->RequestEquipSlot(0);}void AASCharacter::EquipSlot2(){if(Inventory&&!bDowned&&!bEliminated)Inventory->RequestEquipSlot(1);}void AASCharacter::EquipSlot3(){if(Inventory&&!bDowned&&!bEliminated)Inventory->RequestEquipSlot(2);}void AASCharacter::EquipSlot4(){if(Inventory&&!bDowned&&!bEliminated)Inventory->RequestEquipSlot(3);}
void AASCharacter::HandleHealthDeath(AActor*){if(HasAuthority()&&!bDowned&&!bEliminated)EnterDownedState();}
void AASCharacter::EnterDownedState(){if(!HasAuthority()||bDowned||bEliminated)return;GetWorldTimerManager().ClearTimer(BleedoutTimer);bDowned=true;bFireHeld=false;bSprintHeld=false;OnRep_Downed();ForceNetUpdate();GetWorldTimerManager().SetTimer(BleedoutTimer,this,&AASCharacter::FinalizeBleedout,FMath::Max(0.1f,BleedoutSeconds),false);}
bool AASCharacter::TryReviveFrom(APawn*Reviver){if(!HasAuthority()||!bDowned||bEliminated||!Reviver||FVector::DistSquared(Reviver->GetActorLocation(),GetActorLocation())>FMath::Square(ReviveDistance))return false;APlayerState*Mine=GetPlayerState();APlayerState*Theirs=Reviver->GetPlayerState();if(Mine&&Theirs){const class AASPlayerState*ASMine=Cast<class AASPlayerState>(Mine);const class AASPlayerState*ASTheirs=Cast<class AASPlayerState>(Theirs);if(ASMine&&ASTheirs&&ASMine->TeamId!=ASTheirs->TeamId)return false;}if(!Health||!Health->Revive(0.35f))return false;GetWorldTimerManager().ClearTimer(BleedoutTimer);bDowned=false;OnRep_Downed();ForceNetUpdate();return true;}
void AASCharacter::FinalizeBleedout(){if(!HasAuthority()||!bDowned||bEliminated)return;GetWorldTimerManager().ClearTimer(BleedoutTimer);bEliminated=true;bDowned=false;bFireHeld=false;bSprintHeld=false;OnRep_Downed();OnRep_Eliminated();ForceNetUpdate();if(AASGameMode*GameMode=GetWorld()?GetWorld()->GetAuthGameMode<AASGameMode>():nullptr)GameMode->HandlePlayerEliminated(this);}
void AASCharacter::InitializeForRespawn(){if(!HasAuthority())return;GetWorldTimerManager().ClearTimer(BleedoutTimer);bDowned=false;bEliminated=false;bFireHeld=false;bSprintHeld=false;Grenades=MaxGrenades;LastDashTime=-1000.;if(Health)Health->ResetHealth();SetActorHiddenInGame(false);OnRep_Downed();OnRep_Eliminated();ForceNetUpdate();}
void AASCharacter::ApplyLifeState(){UCharacterMovementComponent*Movement=GetCharacterMovement();if(bEliminated){SetActorEnableCollision(false);SetCanBeDamaged(false);if(Movement){Movement->StopMovementImmediately();Movement->DisableMovement();}return;}SetActorEnableCollision(true);SetCanBeDamaged(true);if(!Movement)return;if(bDowned){Movement->StopMovementImmediately();Movement->DisableMovement();}else{if(Movement->MovementMode==MOVE_None)Movement->SetMovementMode(MOVE_Walking);Movement->MaxWalkSpeed=WalkSpeed;}}
void AASCharacter::OnRep_Downed(){ApplyLifeState();OnDownedStateChanged.Broadcast(bDowned);}
void AASCharacter::OnRep_Eliminated(){ApplyLifeState();OnEliminatedStateChanged.Broadcast(bEliminated);}
void AASCharacter::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>&Out)const{Super::GetLifetimeReplicatedProps(Out);DOREPLIFETIME(AASCharacter,bDowned);DOREPLIFETIME(AASCharacter,bEliminated);DOREPLIFETIME(AASCharacter,Grenades);}
